let maplocalleader=','
set encoding=utf-8
set backspace=indent,eol,start
set go+=a
set belloff=all


set clipboard=exclude:.* 
set backupdir=~/.vim/backup//  
set directory=~/.vim/swap//
let s:undoDir = "/tmp/.undodir_" . $USER
if !isdirectory(s:undoDir)
    call mkdir(s:undoDir, "", 0700)
endif
let &undodir=s:undoDir
set undofile
set pastetoggle=<F2> 
set hidden
set whichwrap+=<,>,h,l,[,]

set wrap
set linebreak

set ttymouse=xterm2
set mouse=a

call plug#begin('~/.vim/plugged')
Plug 'lifepillar/vim-mucomplete'
Plug 'jalvesaq/Nvim-R'
Plug 'Raimondi/delimitMate'
"Plug 'python-mode/python-mode', { 'for': 'python', 'branch': 'develop' }
"Plug 'jupyter-vim/jupyter-vim'
Plug 'luochen1990/rainbow'
Plug 'godlygeek/tabular'
"Plug 'plasticboy/vim-markdown'
"Plug 'gabrielelana/vim-markdown'
"Plug 'jpalardy/vim-slime'

"Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
"Plug 'junegunn/fzf.vim'

call plug#end()

let R_app = 'radian'
let R_cmd = 'R'
let R_hl_term = 0
let R_args = []
let R_bracketed_paste = 1"
let R_assign = 0

let g:rainbow_active = 1 "set to 0 if you want to enable it later via :RainbowToggle

set completeopt+=menuone
set completeopt+=noselect
set completeopt+=noinsert
set shortmess+=c
set belloff+=ctrlg
let g:mucomplete#enable_auto_at_startup = 1
let g:mucomplete#chains = { 'default': [  'omni', 'keyn', 'ulti', 'user', 'dict'] }
let g:mucomplete#cycle_all = 1  

" Markdown
"let g:vim_markdown_folding_level = 6
"let g:vim_markdown_folding_disabled = 1
"let g:vim_markdown_toc_autofit = 1

" slime
"let g:slime_target = "vimterminal"


" Testen
set wildmenu
